POST http://localhost:3000/auth/register
content-type: application/json

{
  "email": "vladimir@test.com",
  "password": "123456",
  "name": "Vladimir Azpeitia"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "vladimir@test.com",
  "password": "123456"
}